package com.paitao.xmlife.entity;

import java.util.Date;

public class ThirdpartyId {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_id.id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_id.channel
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    private Integer channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_id.user_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_id.open_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_id.union_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_id.create_time
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_id.update_time
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_id.id
     *
     * @return the value of thirdparty_id.id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_id.id
     *
     * @param id the value for thirdparty_id.id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_id.channel
     *
     * @return the value of thirdparty_id.channel
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_id.channel
     *
     * @param channel the value for thirdparty_id.channel
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_id.user_id
     *
     * @return the value of thirdparty_id.user_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_id.user_id
     *
     * @param userId the value for thirdparty_id.user_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_id.open_id
     *
     * @return the value of thirdparty_id.open_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_id.open_id
     *
     * @param openId the value for thirdparty_id.open_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_id.union_id
     *
     * @return the value of thirdparty_id.union_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_id.union_id
     *
     * @param unionId the value for thirdparty_id.union_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_id.create_time
     *
     * @return the value of thirdparty_id.create_time
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_id.create_time
     *
     * @param createTime the value for thirdparty_id.create_time
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_id.update_time
     *
     * @return the value of thirdparty_id.update_time
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_id.update_time
     *
     * @param updateTime the value for thirdparty_id.update_time
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}