package com.paitao.xmlife.dao;

import com.paitao.xmlife.entity.ThirdpartyId;
import com.paitao.xmlife.entity.ThirdpartyIdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ThirdpartyIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    int countByExample(ThirdpartyIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    int deleteByExample(ThirdpartyIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    int insert(ThirdpartyId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    int insertSelective(ThirdpartyId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    List<ThirdpartyId> selectByExampleWithRowbounds(ThirdpartyIdExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    List<ThirdpartyId> selectByExample(ThirdpartyIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    ThirdpartyId selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    int updateByExampleSelective(@Param("record") ThirdpartyId record, @Param("example") ThirdpartyIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    int updateByExample(@Param("record") ThirdpartyId record, @Param("example") ThirdpartyIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    int updateByPrimaryKeySelective(ThirdpartyId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_id
     *
     * @mbggenerated Wed Dec 09 17:04:18 CST 2015
     */
    int updateByPrimaryKey(ThirdpartyId record);
}